# Generated by Django 3.0.3 on 2020-03-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Girl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('girl_count', models.IntegerField(verbose_name='Номер')),
                ('girl_name', models.CharField(max_length=50, verbose_name='Имя и фамилия')),
            ],
        ),
    ]
